name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.2

      - name: Set up JDK
        uses: actions/setup-java@v3.5.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3.1.0
        with:
          name: APK
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload lint report
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Lint report
          path: app/build/reports/lint-results-debug.html
